var classes = [
    {
        "name": "App\\Calculator\\Parser\\ArgumentParser",
        "interface": false,
        "methods": [
            {
                "name": "parse",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 117,
        "vocabulary": 45,
        "volume": 642.55,
        "difficulty": 11,
        "effort": 7068.01,
        "level": 0.09,
        "bugs": 0.21,
        "time": 393,
        "intelligentContent": 58.41,
        "number_operators": 40,
        "number_operands": 77,
        "number_operators_unique": 10,
        "number_operands_unique": 35,
        "cloc": 12,
        "loc": 58,
        "lloc": 46,
        "mi": 75.38,
        "mIwoC": 42.99,
        "commentWeight": 32.39,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Calculator\\Calculator",
        "interface": false,
        "methods": [
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "multiply",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 12,
        "volume": 103.96,
        "difficulty": 4.5,
        "effort": 467.84,
        "level": 0.22,
        "bugs": 0.03,
        "time": 26,
        "intelligentContent": 23.1,
        "number_operators": 11,
        "number_operands": 18,
        "number_operators_unique": 4,
        "number_operands_unique": 8,
        "cloc": 17,
        "loc": 46,
        "lloc": 29,
        "mi": 94,
        "mIwoC": 53.57,
        "commentWeight": 40.43,
        "kanDefect": 0.51,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.44,
        "relativeSystemComplexity": 6.44,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 7.33,
        "totalSystemComplexity": 19.33,
        "pageRank": 0.5,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]